### ISSUE TITLE
cloudforce.com not supported, Salesforce menu inspector doesn't appear

### ISSUE THREAD

**Issue by kalius** [sorenkrabbe/Chrome-Salesforce-inspector#129] opened 2018-05-21 12:34 UTC
Hi,

first I have to thank you, since this is daily used plugin. It saves a lot of time!

Is it possible to support cloudforce.com domain as well? This is domain used for trialforce SF projects.
Example:
![image](https://user-images.githubusercontent.com/786783/40307839-58c28e24-5d04-11e8-969e-fb824873501e.png)

**Comment by PavelCZE** [comment] 2019-01-31 10:15
Duplicate of #118

**Closed** 2019-05-04 10:45 UTC
