### ISSUE TITLE
LEX support

### ISSUE THREAD

**Issue by AlexanderSchaetzle** [sorenkrabbe/Chrome-Salesforce-inspector#59] opened 2015-12-16 15:01 UTC
Hi there,

unfortunately the inspector is not supported in LEX (for metadata and all data).
Would be awesome to get it there as well!

**Comment by jesperkristensen** [comment] 2016-01-09 20:05
I agree, but I am closing this issue since it is a duplicate of Issue #47.

**Closed** 2016-01-09 20:07 UTC
